#pragma once
#include "Window.h"
#include "Math.h"
#include "Vector2.h"
#include "Figure.h"

#include "TimeManager.h"
#include "Input.h"
#include "CameraManager.h"
#include "D3DRenderer.h"
#include "D2DRenderer.h"
#include "Image.h"
#include "ImageManager.h"
#include "SceneManager.h"

#include "SceneBase.h"
#include "ObjectPool.h"
#include "UpdatePool.h"
#include "RenderPool.h"
#include "Physics.h"
#include "MessageManager.h"
#include "SoundManager.h"
#include "DebugSystem.h"